version: '3.9'

services:
  client :
    build: client 
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  genre:
    build: genre
    ports:
      - '4001:4001'
    volumes:
      - ./genre:/usr/app
      - /usr/app/node_modules
  detail:
    build: detail
    ports:
      - '4004:4004'
    volumes:
      - ./detail:/usr/app
      - /usr/app/node_modules
  event-bus:
    build: event-bus
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
  query:
    build: query
    ports:
      - '4002:4002'
    volumes:
      - ./query:/usr/app
      - /usr/app/node_modules

  genre-db:
    image: mongo:latest
    volumes:
      - genre-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  genre-data:
