version: '3.9'

services:
  client :
    build: client 
    ports:
      - '3000:3000'
  genre:
    build: genre
    ports:
      - '4001:4001'
  detail:
    build: detail
    ports:
      - '4004:4004'
  event-bus:
    build: event-bus
  query:
    build: query
    ports:
      - '4002:4002'
